/* run the views that were generated previously to produce the reports for each */

SELECT * FROM CATCHY_SLOGANS;

SELECT * FROM I_SEE_DEAD_PEOPLE ORDER BY PersonLastName;

SELECT * FROM ACTORS ORDER BY PersonLastName;

SELECT * FROM FUNNY_LIKE_A_CLOWN;

SELECT * FROM SMALL_TOWN_WINNERS;

SELECT * FROM THIRTY_MINUTE_EPISODES;

SELECT * FROM ACTOR_EPISODES;

SELECT * FROM FOREIGN_DRAMA_RUNNER_UPS ORDER BY LanguageName, ShowName;
